id: P007020
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 12:36:40.916754
source_metadata:
  id: bdr:W3CN3344
  title: སི་ཏུའི་འགྲེལ་ཆེན།
  author: ''
  volumes:
    83394fd8540c4b81b65e672042ae3939:
      image_group_id: I3CN3448
      title: Volume 1 of su tu'i 'grel chen/
      volume_number: 1
      total_pages: 296
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
