id: P007020
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN3344
  title: སི་ཏུའི་འགྲེལ་ཆེན།
  author: ''
  volumes:
    96665ed79f4f41b8a4b1a3134c85ef57:
      image_group_id: I3CN3448
      title: ''
      volume_number: 1
      total_pages: 296
ebook_metadata:
  title: སི་ཏུའི་འགྲེལ་ཆེན།
  author: ''
  sku: P007020
  cover: cover.jpg
  layers:
  - pagination
